// <auto-generated />
using System;
using GEPCP_Ferreteria_El_Pana.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GEPCP_Ferreteria_El_Pana.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317024940_RedisenoCompleto")]
    partial class RedisenoCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Comision", b =>
                {
                    b.Property<int>("ComisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComisionId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ComisionId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Comisiones");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.CreditoFerreteria", b =>
                {
                    b.Property<int>("CreditoFerreteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreditoFerreteriaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CuotaQuincenal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCredito")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CreditoFerreteriaId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("CreditosFerreteria");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoJornada")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Feriado", b =>
                {
                    b.Property<int>("FeriadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeriadoId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("FeriadoId");

                    b.ToTable("Feriados");

                    b.HasData(
                        new
                        {
                            FeriadoId = 1,
                            Fecha = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Año Nuevo",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 2,
                            Fecha = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Jueves Santo",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 3,
                            Fecha = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Viernes Santo",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 4,
                            Fecha = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dia de Juan Santamaria",
                            Tipo = 2
                        },
                        new
                        {
                            FeriadoId = 5,
                            Fecha = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dia del Trabajador",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 6,
                            Fecha = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Anexion Guanacaste",
                            Tipo = 2
                        },
                        new
                        {
                            FeriadoId = 7,
                            Fecha = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Virgen de los Angeles",
                            Tipo = 2
                        },
                        new
                        {
                            FeriadoId = 8,
                            Fecha = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dia de la Madre",
                            Tipo = 2
                        },
                        new
                        {
                            FeriadoId = 9,
                            Fecha = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dia de la Independencia",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 10,
                            Fecha = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Navidad",
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.HorasExtras", b =>
                {
                    b.Property<int>("HorasExtrasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorasExtrasId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalHoras")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HorasExtrasId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PeriodoPagoId");

                    b.ToTable("HorasExtras");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Incapacidad", b =>
                {
                    b.Property<int>("IncapacidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncapacidadId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("Entidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoPorDia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PorcentajePago")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ResponsablePago")
                        .HasColumnType("int");

                    b.Property<string>("TipoIncapacidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TiqueteCCSS")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IncapacidadId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Incapacidades");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PagoFeriado", b =>
                {
                    b.Property<int>("PagoFeriadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoFeriadoId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("FeriadoId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodoPagoId")
                        .HasColumnType("int");

                    b.HasKey("PagoFeriadoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("FeriadoId");

                    b.HasIndex("PeriodoPagoId");

                    b.ToTable("PagosFeriado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", b =>
                {
                    b.Property<int>("PeriodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodoPagoId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("Quincena")
                        .HasColumnType("int");

                    b.HasKey("PeriodoPagoId");

                    b.ToTable("PeriodosPago");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Planilla", b =>
                {
                    b.Property<int>("PlanillaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanillaId"));

                    b.Property<decimal>("Deducciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanillaId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PlanillaEmpleado", b =>
                {
                    b.Property<int>("PlanillaEmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanillaEmpleadoId"));

                    b.Property<decimal>("AumentoAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeduccionCCSS")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeduccionCreditoFerreteria")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeduccionHorasNoLaboradas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeduccionIncapacidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeduccionPrestamos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<decimal>("HorasExtras")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasNoLaboradas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasOrdinarias")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoFeriados")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoHorasExtras")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetoAPagar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtrasDeducciones")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeCCSS")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SalarioOrdinario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeducciones")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDevengado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorHoraExtra")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanillaEmpleadoId");

                    b.HasIndex("PeriodoPagoId");

                    b.HasIndex("EmpleadoId", "PeriodoPagoId")
                        .IsUnique();

                    b.ToTable("PlanillasEmpleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CuotaMensual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Cuotas")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PrestamoId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Puesto", b =>
                {
                    b.Property<int>("PuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PuestoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PuestoId");

                    b.ToTable("Puestos");

                    b.HasData(
                        new
                        {
                            PuestoId = 1,
                            Activo = true,
                            Nombre = "Encargada de RR.H.H.",
                            SalarioBase = 450000m
                        },
                        new
                        {
                            PuestoId = 2,
                            Activo = true,
                            Nombre = "Vendedor",
                            SalarioBase = 380000m
                        },
                        new
                        {
                            PuestoId = 3,
                            Activo = true,
                            Nombre = "Conductor (TOSC)",
                            SalarioBase = 436585m
                        },
                        new
                        {
                            PuestoId = 4,
                            Activo = true,
                            Nombre = "Bodeguero (TONCG)",
                            SalarioBase = 447778m
                        },
                        new
                        {
                            PuestoId = 5,
                            Activo = true,
                            Nombre = "Cajero (TOCG)",
                            SalarioBase = 447778m
                        },
                        new
                        {
                            PuestoId = 6,
                            Activo = true,
                            Nombre = "Asistente (TOCG)",
                            SalarioBase = 410855m
                        },
                        new
                        {
                            PuestoId = 7,
                            Activo = true,
                            Nombre = "Proveedor (TOCG)",
                            SalarioBase = 492556m
                        });
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Nombre = "RRHH"
                        },
                        new
                        {
                            RolId = 2,
                            Nombre = "Jefatura"
                        });
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            NombreCompleto = "Administrador RRHH",
                            NombreUsuario = "admin.rrhh",
                            PasswordHash = "$2a$11$/mJGbQrxHo3bDUtdY6MWoeaJc/6aYPE7EG9ukr6ln9mNupX3Y8Wz.",
                            Rol = "RRHH"
                        },
                        new
                        {
                            UsuarioId = 2,
                            NombreCompleto = "Usuario Jefatura",
                            NombreUsuario = "jefatura",
                            PasswordHash = "$2a$11$T72F0Mu8ocYejSTck6bprueMSoi5WgVtSD.hIraw5PvhnjDde6rD6",
                            Rol = "Jefatura"
                        });
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Comision", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("Comisiones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.CreditoFerreteria", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("CreditosFerreteria")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.HorasExtras", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("HorasExtras")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", "PeriodoPago")
                        .WithMany("HorasExtras")
                        .HasForeignKey("PeriodoPagoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("PeriodoPago");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Incapacidad", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("Incapacidades")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PagoFeriado", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("PagosFeriado")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Feriado", "Feriado")
                        .WithMany("PagosFeriado")
                        .HasForeignKey("FeriadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", "PeriodoPago")
                        .WithMany("PagosFeriado")
                        .HasForeignKey("PeriodoPagoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Feriado");

                    b.Navigation("PeriodoPago");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Planilla", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("Planillas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PlanillaEmpleado", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("PlanillasEmpleado")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", "PeriodoPago")
                        .WithMany("PlanillasEmpleado")
                        .HasForeignKey("PeriodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("PeriodoPago");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Prestamo", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("Prestamos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Empleado", b =>
                {
                    b.Navigation("Comisiones");

                    b.Navigation("CreditosFerreteria");

                    b.Navigation("HorasExtras");

                    b.Navigation("Incapacidades");

                    b.Navigation("PagosFeriado");

                    b.Navigation("Planillas");

                    b.Navigation("PlanillasEmpleado");

                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Feriado", b =>
                {
                    b.Navigation("PagosFeriado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", b =>
                {
                    b.Navigation("HorasExtras");

                    b.Navigation("PagosFeriado");

                    b.Navigation("PlanillasEmpleado");
                });
#pragma warning restore 612, 618
        }
    }
}
