// <auto-generated />
using System;
using GEPCP_Ferreteria_El_Pana.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GEPCP_Ferreteria_El_Pana.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419040831_ActualizarCCSS2026_IVM433")]
    partial class ActualizarCCSS2026_IVM433
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.AbonoCreditoFerreteria", b =>
                {
                    b.Property<int>("AbonoCreditoFerreteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreditoFerreteriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAbono")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("AbonoCreditoFerreteriaId");

                    b.HasIndex("CreditoFerreteriaId");

                    b.ToTable("AbonosCreditoFerreteria");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.AbonoPrestamo", b =>
                {
                    b.Property<int>("AbonoPrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAbono")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AbonoPrestamoId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("AbonosPrestamo");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Aguinaldo", b =>
                {
                    b.Property<int>("AguinaldoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("AguinaldoId");

                    b.HasIndex("EmpleadoId", "Anio")
                        .IsUnique();

                    b.ToTable("Aguinaldos");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Comision", b =>
                {
                    b.Property<int>("ComisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PeriodoPagoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComisionId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PeriodoPagoId");

                    b.ToTable("Comisiones");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.CreditoFerreteria", b =>
                {
                    b.Property<int>("CreditoFerreteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CuotaQuincenal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCredito")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("CreditoFerreteriaId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("CreditosFerreteria");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactoEmergenciaNombre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactoEmergenciaTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionCanton")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionDistrito")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionExacta")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionProvincia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimientoContrato")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaPago")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumHijos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroCuenta")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TieneConyuge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoContrato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoJornada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPago")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Feriado", b =>
                {
                    b.Property<int>("FeriadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeriadoId");

                    b.ToTable("Feriados");

                    b.HasData(
                        new
                        {
                            FeriadoId = 1,
                            Fecha = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Año Nuevo",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 2,
                            Fecha = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Jueves Santo",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 3,
                            Fecha = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Viernes Santo",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 4,
                            Fecha = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dia de Juan Santamaria",
                            Tipo = 2
                        },
                        new
                        {
                            FeriadoId = 5,
                            Fecha = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dia del Trabajador",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 6,
                            Fecha = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Anexion Guanacaste",
                            Tipo = 2
                        },
                        new
                        {
                            FeriadoId = 7,
                            Fecha = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Virgen de los Angeles",
                            Tipo = 2
                        },
                        new
                        {
                            FeriadoId = 8,
                            Fecha = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dia de la Madre",
                            Tipo = 2
                        },
                        new
                        {
                            FeriadoId = 9,
                            Fecha = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Dia de la Independencia",
                            Tipo = 1
                        },
                        new
                        {
                            FeriadoId = 10,
                            Fecha = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Navidad",
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.HistorialSalario", b =>
                {
                    b.Property<int>("HistorialSalarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioAnterior")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioNuevo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("HistorialSalarioId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("HistorialSalarios");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.HorasExtras", b =>
                {
                    b.Property<int>("HorasExtrasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodoPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHoras")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("HorasExtrasId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PeriodoPagoId");

                    b.ToTable("HorasExtras");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Incapacidad", b =>
                {
                    b.Property<int>("IncapacidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasPagadosPatrono")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Entidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoPorDia")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajePago")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponsablePago")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoIncapacidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TiqueteCCSS")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalDias")
                        .HasColumnType("INTEGER");

                    b.HasKey("IncapacidadId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Incapacidades");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PagoFeriado", b =>
                {
                    b.Property<int>("PagoFeriadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeriadoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodoPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Trabajado")
                        .HasColumnType("INTEGER");

                    b.HasKey("PagoFeriadoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("FeriadoId");

                    b.HasIndex("PeriodoPagoId");

                    b.ToTable("PagosFeriado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", b =>
                {
                    b.Property<int>("PeriodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_CreditoConyuge")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_CreditoHijo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo1_Hasta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo2_Desde")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo2_Hasta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo2_Porcentaje")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo3_Desde")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo3_Hasta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo3_Porcentaje")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo4_Desde")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo4_Hasta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo4_Porcentaje")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo5_Desde")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ISR_Tramo5_Porcentaje")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeBP")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeCCSS")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeIVM")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeSEM")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quincena")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPeriodo")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeriodoPagoId");

                    b.ToTable("PeriodosPago");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Planilla", b =>
                {
                    b.Property<int>("PlanillaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Deducciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pagada")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanillaId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PlanillaEmpleado", b =>
                {
                    b.Property<int>("PlanillaEmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AumentoAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseImponibleRenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeduccionCCSS")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeduccionCreditoFerreteria")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeduccionHorasNoLaboradas")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeduccionIncapacidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeduccionPrestamos")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeduccionRenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeduccionVacaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionOtrasDeducciones")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HorasExtras")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasNoLaboradas")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasOrdinarias")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoFeriados")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoHorasExtras")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetoAPagar")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OtrasDeducciones")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodoPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeCCSS")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioOrdinario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDeducciones")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDevengado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHora")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHoraExtra")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("PlanillaEmpleadoId");

                    b.HasIndex("PeriodoPagoId");

                    b.HasIndex("EmpleadoId", "PeriodoPagoId")
                        .IsUnique();

                    b.ToTable("PlanillasEmpleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CuotaMensual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Cuotas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PrestamoId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Puesto", b =>
                {
                    b.Property<int>("PuestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PuestoId");

                    b.ToTable("Puestos");

                    b.HasData(
                        new
                        {
                            PuestoId = 1,
                            Activo = true,
                            Nombre = "Encargada de RR.H.H.",
                            SalarioBase = 450000m
                        },
                        new
                        {
                            PuestoId = 2,
                            Activo = true,
                            Nombre = "Vendedor",
                            SalarioBase = 380000m
                        });
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.RegistroAuditoria", b =>
                {
                    b.Property<int>("RegistroAuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RegistroAuditoriaId");

                    b.ToTable("RegistrosAuditoria");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RolId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Nombre = "RRHH"
                        },
                        new
                        {
                            RolId = 2,
                            Nombre = "Jefatura"
                        });
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenRecuperacion")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            CorreoElectronico = "solerahilario207@gmail.com",
                            NombreCompleto = "Administrador RRHH",
                            NombreUsuario = "admin.rrhh",
                            PasswordHash = "$2a$11$/mJGbQrxHo3bDUtdY6MWoeaJc/6aYPE7EG9ukr6ln9mNupX3Y8Wz.",
                            Rol = "RRHH"
                        },
                        new
                        {
                            UsuarioId = 2,
                            CorreoElectronico = "solerahilario207@gmail.com",
                            NombreCompleto = "Usuario Jefatura",
                            NombreUsuario = "jefatura",
                            PasswordHash = "$2a$11$T72F0Mu8ocYejSTck6bprueMSoi5WgVtSD.hIraw5PvhnjDde6rD6",
                            Rol = "Jefatura"
                        });
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Vacacion", b =>
                {
                    b.Property<int>("VacacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiasDisponiblesAlRegistrar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiasHabiles")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoDeducido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioDiario")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("VacacionId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Vacaciones");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.AbonoCreditoFerreteria", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.CreditoFerreteria", "CreditoFerreteria")
                        .WithMany("AbonosCreditoFerreteria")
                        .HasForeignKey("CreditoFerreteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditoFerreteria");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.AbonoPrestamo", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Prestamo", "Prestamo")
                        .WithMany("AbonosPrestamo")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Aguinaldo", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Comision", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("Comisiones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", "PeriodoPago")
                        .WithMany()
                        .HasForeignKey("PeriodoPagoId");

                    b.Navigation("Empleado");

                    b.Navigation("PeriodoPago");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.CreditoFerreteria", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("CreditosFerreteria")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.HistorialSalario", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("HistorialSalarios")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.HorasExtras", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("HorasExtras")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", "PeriodoPago")
                        .WithMany("HorasExtras")
                        .HasForeignKey("PeriodoPagoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("PeriodoPago");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Incapacidad", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("Incapacidades")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PagoFeriado", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("PagosFeriado")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Feriado", "Feriado")
                        .WithMany("PagosFeriado")
                        .HasForeignKey("FeriadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", "PeriodoPago")
                        .WithMany("PagosFeriado")
                        .HasForeignKey("PeriodoPagoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Feriado");

                    b.Navigation("PeriodoPago");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Planilla", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("Planillas")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PlanillaEmpleado", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("PlanillasEmpleado")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", "PeriodoPago")
                        .WithMany("PlanillasEmpleado")
                        .HasForeignKey("PeriodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("PeriodoPago");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Prestamo", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("Prestamos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Vacacion", b =>
                {
                    b.HasOne("GEPCP_Ferreteria_El_Pana.Models.Empleado", "Empleado")
                        .WithMany("Vacaciones")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.CreditoFerreteria", b =>
                {
                    b.Navigation("AbonosCreditoFerreteria");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Empleado", b =>
                {
                    b.Navigation("Comisiones");

                    b.Navigation("CreditosFerreteria");

                    b.Navigation("HistorialSalarios");

                    b.Navigation("HorasExtras");

                    b.Navigation("Incapacidades");

                    b.Navigation("PagosFeriado");

                    b.Navigation("Planillas");

                    b.Navigation("PlanillasEmpleado");

                    b.Navigation("Prestamos");

                    b.Navigation("Vacaciones");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Feriado", b =>
                {
                    b.Navigation("PagosFeriado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.PeriodoPago", b =>
                {
                    b.Navigation("HorasExtras");

                    b.Navigation("PagosFeriado");

                    b.Navigation("PlanillasEmpleado");
                });

            modelBuilder.Entity("GEPCP_Ferreteria_El_Pana.Models.Prestamo", b =>
                {
                    b.Navigation("AbonosPrestamo");
                });
#pragma warning restore 612, 618
        }
    }
}
